# Google App Engine config file
# -----------------------------
# See https://cloud.google.com/appengine/docs/standard/python3/config/appref

# Recommended to set to Python 3.7 runtime or later
runtime: python37

# Set App Engine instance class (defaults to F1)
# See https://cloud.google.com/appengine/docs/standard/#instance_classes
instance_class: F1

handlers:
  # This configures Google App Engine to serve the files in the app's static
  # directory.

- url: /static
  static_dir: app/static

  # This handler routes all requests not caught above to your main app. It is
  # required when static routes are defined, but can be omitted (along with
  # the entire handlers section) when there are no static files defined.
- url: /.*
  script: auto

env_variables:
    GOOGLE_CLOUD_PROJECT: gae-cloud-asu
    CLOUD_STORAGE_BUCKET: gae-cloud-asu.appspot.com
    CLOUD_SQL_CONNECTION_NAME: gae-cloud-asu:us-west4:clouddb
    CLOUD_URL: https://gae-cloud-asu.wn.r.appspot.com
    DB_USER: master
    DB_PASS: 46LyfcwwxCK3dDJq
    DB_NAME: billing
    PUBSUB_TOPIC: ocr
    PUBSUB_VERIFICATION_TOKEN: 1234abc
    
# Set entrypoint to locate Flask app, which is 'application' in module app/__init__.py
# Configure gunicorn worker count via --workers arg based on the App Engine instance class
# See https://cloud.google.com/appengine/docs/standard/python3/runtime#application_startup
entrypoint: gunicorn --workers 1 --worker-class gevent --bind :$PORT app:application
