"""empty message

Revision ID: 26f9de097d30
Revises: fea1d8787245
Create Date: 2020-05-01 01:31:38.164671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26f9de097d30'
down_revision = 'fea1d8787245'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('date_posted', sa.DateTime(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imageName', sa.String(length=100), nullable=False),
    sa.Column('imageUrl', sa.String(length=1000), nullable=False),
    sa.Column('imageDate', sa.DateTime(), nullable=True),
    sa.Column('notify', sa.Boolean(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('image_file', sa.String(length=20), nullable=False))
    op.add_column('user', sa.Column('password', sa.String(length=60), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password')
    op.drop_column('user', 'image_file')
    op.drop_table('user_image')
    op.drop_table('post')
    # ### end Alembic commands ###
