"""empty message

Revision ID: 9f863ff4c605
Revises: 00b9ac316ac7
Create Date: 2020-05-03 17:15:15.458976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f863ff4c605'
down_revision = '00b9ac316ac7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grocery_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('productName', sa.String(length=300), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('grocery_list')
    # ### end Alembic commands ###
